### ISSUE TITLE
RSS feed to App?

### ISSUE THREAD

**Issue by lidafarmer** [imme5150/refinery_csa_app#1]
Hello - 

I'm really interested in using this app for our CSA.  I'm just wondering if I'd be able to get the content I typically create each week on my blog easily on this app.  I've used a blogger blog to create a weekly "news from the farm" with the crops in the box for the past 8 years which I send out via an RSS eNewletter to members with MailChimp.  Would I be able to do a similar thing with this app so I'm writing the newsletter in one place and not cutting and pasting into the app too?  I appreaciate any ideas you may have.

**Comment by imme5150** [comment]
This functionality isn't set up on the app, but it wouldn't be too hard to add.  http://feedjira.com/ would be a good starting point.  I can do the work to set it up, but would need to get paid for my time.  I'm happy to work up an estimate for you if you want.  Copy and paste is definitely the simplest solution, although it's not ideal.
